<script lang="ts">
 import PageHeader from '$lib/admin/PageHeader.svelte'; import EmptyState from '$lib/admin/EmptyState.svelte'; import StatusBadge from '$lib/admin/StatusBadge.svelte'; import { formatDate } from '$lib/admin/format'; import { Button } from '$lib/components/ui/button'; import { Input } from '$lib/components/ui/input'; import { Alert, AlertDescription } from '$lib/components/ui/alert'; import { Plus, Search, Pencil, Eye, Send, Archive, Trash2 } from '@lucide/svelte'; import { enhance } from '$app/forms'; import { invalidateAll } from '$app/navigation'; import { toast } from 'svelte-sonner';
 let {data,form}=$props();let query=$state('');let status=$state('ALL');let filtered=$derived(data.articles.filter((a)=>`${a.title} ${a.author?.name||''}`.toLowerCase().includes(query.toLowerCase())&&(status==='ALL'||a.status===status)));const done=(message:string)=>()=>async({update}:any)=>{await update();await invalidateAll();toast.success(message)};
</script>
<PageHeader title="Artikel" description="Ruang redaksi untuk menulis, meninjau, dan menerbitkan artikel BEM UNAIR."><Button href="/admin/articles/new" class="bg-orange-500"><Plus/>Tulis artikel</Button></PageHeader>
{#if form?.error}<Alert variant="destructive" class="mb-4"><AlertDescription>{form.error}</AlertDescription></Alert>{/if}
<div class="mb-5 grid gap-3 md:grid-cols-[1fr_180px]"><div class="relative"><Search class="absolute left-2.5 top-2 size-4 text-black-200"/><Input bind:value={query} placeholder="Cari judul atau penulis..." class="pl-8"/></div><select bind:value={status} class="h-9 rounded-lg border bg-card px-3 text-sm"><option value="ALL">Semua status</option><option>DRAFT</option><option>PUBLISHED</option></select></div>
{#if filtered.length}<div class="grid gap-4 xl:grid-cols-2">{#each filtered as article}<article class="overflow-hidden rounded-xl border bg-card"><div class="grid min-h-44 grid-cols-[140px_1fr]">{#if article.cover_image}<img src={article.cover_image} alt="" class="h-full w-full object-cover"/>{:else}<div class="grid place-items-center bg-blue-500 px-4 text-center font-serif text-lg font-semibold text-white">BEM UNAIR</div>{/if}<div class="flex min-w-0 flex-col p-5"><div class="flex items-center justify-between gap-2"><StatusBadge status={article.status}/><span class="text-xs text-black-200">{formatDate(article.updated_at)}</span></div><h2 class="mt-3 line-clamp-2 font-serif text-xl font-semibold leading-tight">{article.title}</h2><p class="mt-2 line-clamp-2 text-sm text-muted-foreground">{article.excerpt||'Belum ada ringkasan.'}</p><p class="mt-auto pt-3 text-xs text-black-200">{article.author?.name||'—'}</p></div></div><div class="flex flex-wrap justify-end gap-1 border-t px-3 py-2"><Button href={`/admin/articles/${article.id}/edit`} variant="ghost" size="sm"><Pencil/>Edit</Button><Button href={`/admin/articles/${article.id}/preview`} variant="ghost" size="sm"><Eye/>Preview</Button><form method="POST" action="?/publish" use:enhance={done(article.status==='PUBLISHED'?'Artikel dijadikan draft':'Artikel dipublikasikan')}><input type="hidden" name="id" value={article.id}/><input type="hidden" name="published" value={article.status!=='PUBLISHED'?'true':'false'}/><Button type="submit" variant="ghost" size="sm">{#if article.status==='PUBLISHED'}<Archive/>Draft{:else}<Send/>Terbitkan{/if}</Button></form><form method="POST" action="?/delete" use:enhance={done('Artikel dihapus')} onsubmit={(e)=>{if(!confirm('Hapus artikel ini secara permanen?'))e.preventDefault()}}><input type="hidden" name="id" value={article.id}/><Button type="submit" variant="ghost" size="sm" class="text-red-700"><Trash2/></Button></form></div></article>{/each}</div>{:else}<EmptyState title="Belum ada artikel" description="Mulai draft pertama dengan editor redaksi bergaya Notion."/>{/if}
{#if data.meta?.total_pages>1}<div class="mt-6 flex items-center justify-between text-sm"><span>Halaman {data.meta.page} dari {data.meta.total_pages}</span><div class="flex gap-2"><Button href={`?page=${data.meta.page-1}`} variant="outline" disabled={data.meta.page<=1}>Sebelumnya</Button><Button href={`?page=${data.meta.page+1}`} variant="outline" disabled={data.meta.page>=data.meta.total_pages}>Berikutnya</Button></div></div>{/if}
