CREATE TABLE cabinet_terms (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(150) NOT NULL,
  slug VARCHAR(160) NOT NULL,
  tagline VARCHAR(255) NULL,
  description LONGTEXT NULL,
  logo_media_id BIGINT UNSIGNED NULL,
  hero_media_id BIGINT UNSIGNED NULL,
  period_start DATE NULL,
  period_end DATE NULL,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  is_published BOOLEAN NOT NULL DEFAULT FALSE,
  published_at DATETIME(3) NULL,
  meta_title VARCHAR(180) NULL,
  meta_description VARCHAR(255) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY idx_cabinet_terms_slug (slug),
  KEY idx_cabinet_terms_public (is_active, is_published)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE media_assets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uploaded_by BIGINT UNSIGNED NULL,
  imagekit_file_id VARCHAR(100) NOT NULL,
  file_path VARCHAR(1000) NULL,
  url VARCHAR(1000) NOT NULL,
  thumbnail_url VARCHAR(1000) NULL,
  name VARCHAR(255) NOT NULL,
  alt_text VARCHAR(255) NOT NULL,
  caption TEXT NULL,
  mime_type VARCHAR(120) NOT NULL,
  size_bytes BIGINT UNSIGNED NOT NULL,
  width INT UNSIGNED NULL,
  height INT UNSIGNED NULL,
  purpose VARCHAR(80) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY idx_media_assets_file_id (imagekit_file_id),
  KEY idx_media_assets_uploader (uploaded_by, status),
  CONSTRAINT fk_media_assets_uploader FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE cabinet_terms
  ADD CONSTRAINT fk_cabinet_terms_logo FOREIGN KEY (logo_media_id) REFERENCES media_assets(id) ON DELETE RESTRICT,
  ADD CONSTRAINT fk_cabinet_terms_hero FOREIGN KEY (hero_media_id) REFERENCES media_assets(id) ON DELETE RESTRICT;

ALTER TABLE ministries
  ADD COLUMN cabinet_term_id BIGINT UNSIGNED NULL AFTER name,
  ADD COLUMN parent_id BIGINT UNSIGNED NULL AFTER cabinet_term_id,
  ADD COLUMN unit_type VARCHAR(20) NOT NULL DEFAULT 'KEMENTERIAN' AFTER parent_id,
  ADD COLUMN slug VARCHAR(160) NULL AFTER unit_type,
  ADD COLUMN short_name VARCHAR(80) NULL AFTER slug,
  ADD COLUMN description TEXT NULL AFTER short_name,
  ADD COLUMN vision TEXT NULL AFTER description,
  ADD COLUMN mission TEXT NULL AFTER vision,
  ADD COLUMN logo_media_id BIGINT UNSIGNED NULL AFTER mission,
  ADD COLUMN cover_media_id BIGINT UNSIGNED NULL AFTER logo_media_id,
  ADD COLUMN display_order INT UNSIGNED NOT NULL DEFAULT 0 AFTER cover_media_id,
  ADD COLUMN is_published BOOLEAN NOT NULL DEFAULT FALSE AFTER is_active,
  ADD COLUMN published_at DATETIME(3) NULL AFTER is_published,
  ADD UNIQUE KEY idx_ministries_cabinet_slug (cabinet_term_id, slug),
  ADD KEY idx_ministries_cabinet_parent_order (cabinet_term_id, parent_id, display_order),
  ADD KEY idx_ministries_public (cabinet_term_id, unit_type, is_active, is_published),
  ADD CONSTRAINT fk_ministries_cabinet FOREIGN KEY (cabinet_term_id) REFERENCES cabinet_terms(id) ON DELETE RESTRICT,
  ADD CONSTRAINT fk_ministries_parent FOREIGN KEY (parent_id) REFERENCES ministries(id) ON DELETE RESTRICT,
  ADD CONSTRAINT fk_ministries_logo FOREIGN KEY (logo_media_id) REFERENCES media_assets(id) ON DELETE RESTRICT,
  ADD CONSTRAINT fk_ministries_cover FOREIGN KEY (cover_media_id) REFERENCES media_assets(id) ON DELETE RESTRICT;

CREATE TABLE organization_members (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ministry_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  name VARCHAR(120) NOT NULL,
  position VARCHAR(120) NOT NULL,
  position_type VARCHAR(40) NOT NULL,
  email_public VARCHAR(150) NULL,
  phone_public VARCHAR(30) NULL,
  biography TEXT NULL,
  quote TEXT NULL,
  photo_media_id BIGINT UNSIGNED NULL,
  display_order INT UNSIGNED NOT NULL DEFAULT 0,
  is_leader BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  started_at DATE NULL,
  ended_at DATE NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_organization_members_unit (ministry_id, is_active, display_order),
  KEY idx_organization_members_position (ministry_id, position_type),
  CONSTRAINT fk_organization_members_unit FOREIGN KEY (ministry_id) REFERENCES ministries(id) ON DELETE RESTRICT,
  CONSTRAINT fk_organization_members_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_organization_members_photo FOREIGN KEY (photo_media_id) REFERENCES media_assets(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE user_organization_roles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  ministry_id BIGINT UNSIGNED NOT NULL,
  permission VARCHAR(40) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY idx_user_organization_permission (user_id, ministry_id, permission),
  KEY idx_user_organization_unit (ministry_id, is_active),
  CONSTRAINT fk_user_organization_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_user_organization_unit FOREIGN KEY (ministry_id) REFERENCES ministries(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE work_programs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ministry_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(180) NOT NULL,
  slug VARCHAR(200) NOT NULL,
  short_description VARCHAR(500) NULL,
  description LONGTEXT NULL,
  objectives TEXT NULL,
  target_audience TEXT NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  execution_month VARCHAR(50) NULL,
  lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  cover_media_id BIGINT UNSIGNED NULL,
  display_order INT UNSIGNED NOT NULL DEFAULT 0,
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  is_published BOOLEAN NOT NULL DEFAULT FALSE,
  published_at DATETIME(3) NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  meta_title VARCHAR(180) NULL,
  meta_description VARCHAR(255) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY idx_work_program_unit_slug (ministry_id, slug),
  KEY idx_work_program_public (ministry_id, is_published, display_order),
  KEY idx_work_program_featured (is_featured, is_published),
  CONSTRAINT fk_work_program_unit FOREIGN KEY (ministry_id) REFERENCES ministries(id) ON DELETE RESTRICT,
  CONSTRAINT fk_work_program_cover FOREIGN KEY (cover_media_id) REFERENCES media_assets(id) ON DELETE RESTRICT,
  CONSTRAINT fk_work_program_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_work_program_updater FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE work_program_milestones (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  work_program_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(180) NOT NULL,
  description TEXT NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
  display_order INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_milestones_program_order (work_program_id, display_order),
  CONSTRAINT fk_milestones_program FOREIGN KEY (work_program_id) REFERENCES work_programs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE work_program_documentations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  work_program_id BIGINT UNSIGNED NOT NULL,
  media_asset_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(180) NULL,
  caption TEXT NULL,
  taken_at DATETIME(3) NULL,
  display_order INT UNSIGNED NOT NULL DEFAULT 0,
  is_cover BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY idx_documentations_program_asset (work_program_id, media_asset_id),
  KEY idx_documentations_program_order (work_program_id, display_order),
  CONSTRAINT fk_documentations_program FOREIGN KEY (work_program_id) REFERENCES work_programs(id) ON DELETE CASCADE,
  CONSTRAINT fk_documentations_asset FOREIGN KEY (media_asset_id) REFERENCES media_assets(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
