<script lang="ts">
 import PageHeader from '$lib/admin/PageHeader.svelte'; import EmptyState from '$lib/admin/EmptyState.svelte'; import { Button } from '$lib/components/ui/button'; import { Badge } from '$lib/components/ui/badge'; import * as Dialog from '$lib/components/ui/dialog'; import { Label } from '$lib/components/ui/label'; import { Alert, AlertDescription } from '$lib/components/ui/alert'; import { Plus, ArrowUp, ArrowDown, Trash2, GripVertical } from '@lucide/svelte'; import { enhance } from '$app/forms'; import { invalidateAll } from '$app/navigation'; import { toast } from 'svelte-sonner';
 let {data,form}=$props(); let open=$state(false); let userId=$state(''); let queue=$derived([...data.queue].sort((a,b)=>a.position-b.position)); let available=$derived(data.users.filter((u)=>!data.queue.some((q)=>q.user_id===u.id)));
 const done=(message:string)=>()=>async({update}:any)=>{await update();await invalidateAll();toast.success(message);open=false};
</script>
<PageHeader title="Rotasi PJ Medinfo" description="Urutan pertama adalah PJ aktif yang menerima assignment berikutnya."><Button onclick={()=>open=true} class="bg-blue-500" disabled={!available.length}><Plus/>Tambah PJ</Button></PageHeader>
{#if form?.error}<Alert variant="destructive" class="mb-4"><AlertDescription>{form.error}</AlertDescription></Alert>{/if}
{#if queue.length}<div class="max-w-3xl space-y-3">{#each queue as item,index}<div class:item-current={item.is_current} class="flex items-center gap-3 rounded-xl border bg-card p-3 shadow-sm"><GripVertical class="size-5 text-black-100"/><div class="grid size-9 place-items-center rounded-lg bg-muted font-serif font-semibold">{index+1}</div><div class="min-w-0 flex-1"><div class="flex items-center gap-2"><p class="truncate font-medium">{item.user?.name||`User #${item.user_id}`}</p>{#if item.is_current}<Badge class="bg-orange-500">PJ aktif</Badge>{/if}</div><p class="truncate text-xs text-muted-foreground">{item.user?.ministry||'Tanpa kementerian'} · {item.user?.email||'—'}</p></div><div class="flex gap-1"><form method="POST" action="?/move" use:enhance={done('Urutan diperbarui')}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="direction" value="up"/><Button type="submit" variant="ghost" size="icon" disabled={index===0} aria-label="Naik"><ArrowUp/></Button></form><form method="POST" action="?/move" use:enhance={done('Urutan diperbarui')}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="direction" value="down"/><Button type="submit" variant="ghost" size="icon" disabled={index===queue.length-1} aria-label="Turun"><ArrowDown/></Button></form><form method="POST" action="?/delete" use:enhance={done('PJ dihapus dari antrean')} onsubmit={(e)=>{if(!confirm('Hapus PJ dari rotasi?'))e.preventDefault()}}><input type="hidden" name="id" value={item.id}/><Button type="submit" variant="ghost" size="icon" class="text-red-700" aria-label="Hapus"><Trash2/></Button></form></div></div>{/each}</div>{:else}<EmptyState title="Rotasi PJ masih kosong" description="Tambahkan pengguna agar assignment pengajuan dapat berjalan."/>{/if}
<Dialog.Root bind:open><Dialog.Content><Dialog.Header><Dialog.Title>Tambah PJ ke rotasi</Dialog.Title><Dialog.Description>Pengguna akan ditempatkan pada urutan terakhir.</Dialog.Description></Dialog.Header><form method="POST" action="?/create" use:enhance={done('PJ ditambahkan')} class="space-y-4"><div class="space-y-2"><Label for="user_id">Pengguna</Label><select id="user_id" name="user_id" bind:value={userId} required class="h-9 w-full rounded-lg border bg-card px-3 text-sm"><option value="" disabled>Pilih pengguna</option>{#each available as user}<option value={user.id}>{user.name} · {user.ministry||user.role}</option>{/each}</select></div><Dialog.Footer><Button type="button" variant="outline" onclick={()=>open=false}>Batal</Button><Button type="submit" class="bg-blue-500">Tambahkan</Button></Dialog.Footer></form></Dialog.Content></Dialog.Root>
<style>.item-current{border-color:var(--orange-500);background:linear-gradient(90deg,var(--orange-50) 0,var(--card) 35%)}</style>
