<script lang="ts">
  import PageHeader from '$lib/admin/PageHeader.svelte'; import StatusBadge from '$lib/admin/StatusBadge.svelte'; import { formatDate } from '$lib/admin/format'; import { Button } from '$lib/components/ui/button'; import { Textarea } from '$lib/components/ui/textarea'; import { Label } from '$lib/components/ui/label'; import { Alert, AlertDescription } from '$lib/components/ui/alert'; import { ExternalLink, Trash2 } from '@lucide/svelte'; import { enhance } from '$app/forms'; import { invalidateAll } from '$app/navigation'; import { toast } from 'svelte-sonner';
  let { data, form } = $props(); const row=$derived(data.submission); let rejection=$state(false);
  const update=()=>async({update}:any)=>{await update();await invalidateAll();toast.success('Status berhasil diperbarui')};
  const links=$derived([['Brief',row.brief_link],['Design Drive',row.design_drive_link],['Canva',row.canva_link],['Naskah artikel',row.article_drive_link]].filter(([,url])=>url));
</script>
<PageHeader title={row.title} description={`${row.ministry} · diajukan ${formatDate(row.created_at, true)}`}><StatusBadge status={row.status}/></PageHeader>
{#if form?.error}<Alert variant="destructive" class="mb-4"><AlertDescription>{form.error}</AlertDescription></Alert>{/if}
<div class="grid gap-5 xl:grid-cols-[1fr_340px]">
  <div class="space-y-5"><section class="rounded-xl border bg-card p-6"><p class="mb-2 text-xs font-semibold uppercase tracking-widest text-orange-500">{row.submission_type.replace('_',' / ')}</p><h2 class="font-serif text-2xl font-semibold">Caption & brief</h2><p class="mt-4 whitespace-pre-wrap leading-7 text-black-400">{row.caption}</p>{#if row.additional_notes}<div class="mt-5 border-l-2 border-orange-500 pl-4"><p class="text-xs font-semibold uppercase text-muted-foreground">Catatan tambahan</p><p class="mt-1 whitespace-pre-wrap text-sm">{row.additional_notes}</p></div>{/if}</section>
  <section class="rounded-xl border bg-card p-6"><h2 class="font-serif text-xl font-semibold">Tautan kerja</h2><div class="mt-4 grid gap-2 sm:grid-cols-2">{#each links as link}<Button href={String(link[1])} target="_blank" variant="outline" class="justify-between">{link[0]}<ExternalLink/></Button>{/each}</div></section></div>
  <aside class="space-y-5"><section class="rounded-xl border bg-card p-5"><h2 class="font-serif text-lg font-semibold">Jadwal & penanggung jawab</h2><dl class="mt-4 grid gap-3 text-sm"><div><dt class="text-muted-foreground">Publikasi</dt><dd>{formatDate(row.publish_date)} {row.publish_time || ''}</dd></div><div><dt class="text-muted-foreground">Deadline</dt><dd>{formatDate(row.deadline,true)}</dd></div><div><dt class="text-muted-foreground">Pengaju</dt><dd>{row.submitter?.name || '—'}</dd></div><div><dt class="text-muted-foreground">PJ Medinfo</dt><dd>{row.assigned_pj?.name || 'Belum ditetapkan'}</dd></div></dl></section>
  {#if row.status==='PENDING'}<form method="POST" action="?/status" use:enhance={update} class="rounded-xl border bg-card p-5"><input type="hidden" name="status" value="IN_REVIEW"/><h2 class="font-serif text-lg font-semibold">Mulai peninjauan</h2><p class="my-3 text-sm text-muted-foreground">PJ aktif akan menangani pengajuan ini.</p><Button type="submit" class="w-full bg-blue-500">Tandai sedang ditinjau</Button></form>{:else if row.status==='IN_REVIEW'}<form method="POST" action="?/status" use:enhance={update} class="space-y-3 rounded-xl border bg-card p-5"><h2 class="font-serif text-lg font-semibold">Keputusan</h2>{#if rejection}<Label for="notes">Alasan penolakan</Label><Textarea id="notes" name="notes" required placeholder="Berikan alasan yang dapat ditindaklanjuti..."/>{/if}<div class="grid grid-cols-2 gap-2"><Button type="submit" name="status" value="APPROVED" class="bg-green-700">Setujui</Button><Button type={rejection?'submit':'button'} name="status" value="REJECTED" variant="destructive" onclick={()=>rejection=true}>Tolak</Button></div></form>{/if}
  {#if row.notes}<Alert><AlertDescription><strong>Catatan keputusan:</strong> {row.notes}</AlertDescription></Alert>{/if}
  <form method="POST" action="?/delete" onsubmit={(e)=>{if(!confirm('Hapus pengajuan ini secara permanen?'))e.preventDefault()}}><Button type="submit" variant="ghost" class="w-full text-red-700"><Trash2/>Hapus pengajuan</Button></form></aside>
</div>
