FROM golang:1.25-bookworm

WORKDIR /app

ENV CGO_ENABLED=0
ENV GOPROXY=https://proxy.golang.org,direct
ENV GOTOOLCHAIN=local

# Versi Air yang kompatibel dengan Go 1.25
RUN go install github.com/air-verse/air@v1.66.1

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
