INSERT INTO content_submissions (
  id, submitter_id, ministry, submission_type, title, add_song, caption,
  additional_notes, publish_date, publish_time, design_drive_link, canva_link,
  article_drive_link, deadline, brief_link, assigned_pj_id, status, notes
) VALUES
  (
    900001,
    (SELECT id FROM users WHERE email = 'mentri.psdm@bem.unair.ac.id'),
    'PSDM',
    'FEEDS_REELS',
    'Open Recruitment Volunteer BEM UNAIR',
    'Good Life - OneRepublic',
    'Saatnya bertumbuh dan memberi dampak bersama BEM Universitas Airlangga.',
    'Gunakan visual mahasiswa yang hangat dan inklusif.',
    DATE_ADD(CURRENT_DATE, INTERVAL 5 DAY),
    '18:30',
    'https://drive.google.com/example/design-oprec',
    'https://www.canva.com/example/oprec',
    NULL,
    DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 DAY),
    'https://drive.google.com/example/brief-oprec',
    (SELECT id FROM users WHERE email = 'mentri.medinfo@bem.unair.ac.id'),
    'PENDING_REVIEW',
    NULL
  ),
  (
    900002,
    (SELECT id FROM users WHERE email = 'mentri.sosmas@bem.unair.ac.id'),
    'SOSMAS',
    'INSTASTORY',
    'Donasi Buku untuk Sekolah Mitra',
    NULL,
    'Satu buku dapat membuka ribuan kemungkinan. Mari berbagi akses pengetahuan.',
    'Sertakan progress bar donasi pada slide terakhir.',
    DATE_ADD(CURRENT_DATE, INTERVAL 3 DAY),
    '12:00',
    'https://drive.google.com/example/design-donasi',
    'https://www.canva.com/example/donasi',
    NULL,
    DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 DAY),
    'https://drive.google.com/example/brief-donasi',
    (SELECT id FROM users WHERE email = 'editor.medinfo@bem.unair.ac.id'),
    'PENDING_REVIEW',
    'Copy sedang diselaraskan dengan data penerima.'
  ),
  (
    900003,
    (SELECT id FROM users WHERE email = 'mentri.kesma@bem.unair.ac.id'),
    'KESMA',
    'ARTIKEL',
    'Panduan Akses Layanan Kesejahteraan Mahasiswa',
    NULL,
    'Panduan ringkas layanan kesejahteraan bagi mahasiswa Universitas Airlangga.',
    'Pastikan seluruh tautan layanan sudah diverifikasi.',
    NULL,
    NULL,
    NULL,
    NULL,
    'https://drive.google.com/example/article-kesma',
    DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 4 DAY),
    'https://drive.google.com/example/brief-kesma',
    (SELECT id FROM users WHERE email = 'staf.medinfo@bem.unair.ac.id'),
    'APPROVED',
    'Naskah telah mendapat persetujuan bidang terkait.'
  ),
  (
    900004,
    (SELECT id FROM users WHERE email = 'mentri.psdm@bem.unair.ac.id'),
    'PSDM',
    'FEEDS_REELS',
    'Recap Internal Capacity Building',
    NULL,
    'Terima kasih telah bertumbuh bersama dalam Capacity Building BEM UNAIR.',
    NULL,
    DATE_SUB(CURRENT_DATE, INTERVAL 2 DAY),
    '19:00',
    'https://drive.google.com/example/design-capacity',
    'https://www.canva.com/example/capacity',
    NULL,
    DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY),
    'https://drive.google.com/example/brief-capacity',
    NULL,
    'REJECTED',
    'Materi visual perlu menggunakan dokumentasi resmi kegiatan.'
  )
ON DUPLICATE KEY UPDATE
  submitter_id = VALUES(submitter_id),
  ministry = VALUES(ministry),
  submission_type = VALUES(submission_type),
  title = VALUES(title),
  add_song = VALUES(add_song),
  caption = VALUES(caption),
  additional_notes = VALUES(additional_notes),
  publish_date = VALUES(publish_date),
  publish_time = VALUES(publish_time),
  design_drive_link = VALUES(design_drive_link),
  canva_link = VALUES(canva_link),
  article_drive_link = VALUES(article_drive_link),
  deadline = VALUES(deadline),
  brief_link = VALUES(brief_link),
  assigned_pj_id = VALUES(assigned_pj_id),
  status = VALUES(status),
  notes = VALUES(notes);
