<script lang="ts">
  import PageHeader from '$lib/admin/PageHeader.svelte'; import EmptyState from '$lib/admin/EmptyState.svelte'; import { Button } from '$lib/components/ui/button'; import { Input } from '$lib/components/ui/input'; import { Badge } from '$lib/components/ui/badge'; import * as Table from '$lib/components/ui/table'; import * as Dialog from '$lib/components/ui/dialog'; import { Label } from '$lib/components/ui/label'; import { Alert, AlertDescription } from '$lib/components/ui/alert'; import { Plus, Search, Pencil, Trash2 } from '@lucide/svelte'; import { enhance } from '$app/forms'; import { invalidateAll } from '$app/navigation'; import { toast } from 'svelte-sonner';
  let { data, form } = $props(); let query=$state(''); let open=$state(false); let editing=$state<any>(null);
  let filtered=$derived(data.users.filter((u:any)=>`${u.name} ${u.email} ${u.ministry||''}`.toLowerCase().includes(query.toLowerCase())));
  const done=()=>async({update}:any)=>{await update({reset:false});await invalidateAll();toast.success('Perubahan tersimpan');open=false;editing=null;};
</script>
<PageHeader title="Pengguna" description="Kelola akun admin dan kementerian."><Button onclick={()=>{editing=null;open=true}} class="bg-blue-500"><Plus/>Tambah pengguna</Button></PageHeader>
{#if form?.error}<Alert variant="destructive" class="mb-4"><AlertDescription>{form.error}</AlertDescription></Alert>{/if}
<div class="mb-4 max-w-sm"><div class="relative"><Search class="absolute left-2.5 top-2 size-4 text-black-200"/><Input bind:value={query} placeholder="Cari nama, email, kementerian..." class="pl-8"/></div></div>
{#if filtered.length}<div class="overflow-hidden rounded-xl border bg-card"><Table.Root><Table.Header><Table.Row><Table.Head>Pengguna</Table.Head><Table.Head>Role</Table.Head><Table.Head>Kementerian</Table.Head><Table.Head>Telepon</Table.Head><Table.Head class="w-32 text-right">Aksi</Table.Head></Table.Row></Table.Header><Table.Body>{#each filtered as user}<Table.Row><Table.Cell><p class="font-medium">{user.name}</p><p class="text-xs text-muted-foreground">{user.email}</p></Table.Cell><Table.Cell><Badge variant={user.role==='ADMIN_MEDINFO'?'default':'secondary'}>{user.role}</Badge></Table.Cell><Table.Cell>{user.ministry||'—'}</Table.Cell><Table.Cell>{user.phone||'—'}</Table.Cell><Table.Cell><div class="flex justify-end gap-1"><Button variant="ghost" size="icon" onclick={()=>{editing=user;open=true}} aria-label="Edit"><Pencil/></Button><form method="POST" action="?/delete" use:enhance={done}><input type="hidden" name="id" value={user.id}/><Button type="submit" variant="destructive" size="icon" aria-label="Hapus"><Trash2/></Button></form></div></Table.Cell></Table.Row>{/each}</Table.Body></Table.Root></div>{:else}<EmptyState title="Pengguna tidak ditemukan" description="Ubah kata pencarian atau buat pengguna baru."/>{/if}
<Dialog.Root bind:open><Dialog.Content class="sm:max-w-lg"><Dialog.Header><Dialog.Title>{editing?'Edit pengguna':'Tambah pengguna'}</Dialog.Title><Dialog.Description>Isi identitas dan hak akses pengguna.</Dialog.Description></Dialog.Header><form method="POST" action={editing?'?/update':'?/create'} use:enhance={done} class="space-y-4">{#if editing}<input type="hidden" name="id" value={editing.id}/>{/if}<div class="grid gap-4 sm:grid-cols-2"><div class="space-y-2"><Label for="name">Nama</Label><Input id="name" name="name" value={editing?.name||''} required/></div><div class="space-y-2"><Label for="email">Email</Label><Input id="email" name="email" type="email" value={editing?.email||''} required/></div>{#if !editing}<div class="space-y-2 sm:col-span-2"><Label for="password">Password</Label><Input id="password" name="password" type="password" minlength={8} required/></div>{/if}<div class="space-y-2"><Label for="role">Role</Label><select id="role" name="role" class="h-8 w-full rounded-lg border bg-card px-2 text-sm" value={editing?.role||'ADMIN'}><option value="ADMIN">ADMIN</option><option value="ADMIN_MEDINFO">ADMIN_MEDINFO</option></select></div><div class="space-y-2"><Label for="ministry_choice">Kementerian</Label><select id="ministry_choice" name="ministry_choice" class="h-9 w-full rounded-lg border bg-card px-3 text-sm" value={editing?.ministry_id ? String(editing.ministry_id) : ""}><option value="">Tanpa kementerian</option>{#each data.ministries.filter((ministry) => ministry.is_active) as ministry}<option value={String(ministry.id)}>{ministry.name}</option>{/each}</select></div><div class="space-y-2 sm:col-span-2"><Label for="phone">Nomor WhatsApp</Label><Input id="phone" name="phone" value={editing?.phone||''} placeholder="62812..."/></div></div><Dialog.Footer><Button type="button" variant="outline" onclick={()=>open=false}>Batal</Button><Button type="submit" class="bg-blue-500">Simpan</Button></Dialog.Footer></form></Dialog.Content></Dialog.Root>
