services:
  workspace:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    container_name: bemunair_workspace
    working_dir: /workspace

    command:
      - /bin/sh
      - -c
      - while sleep 1000; do :; done

    volumes:
      - ..:/workspace:cached
      - client_node_modules:/workspace/client/node_modules
      - wa_engine_node_modules:/workspace/wa-engine/node_modules
      - server_go_modules:/go/pkg/mod
      - server_go_build_cache:/home/node/.cache/go-build

    depends_on:
      db:
        condition: service_healthy

    networks:
      - bemunair_net
