FROM node:22-bookworm-slim

WORKDIR /app

ENV NODE_ENV=development
ENV PNPM_HOME=/pnpm
ENV PATH="${PNPM_HOME}:${PATH}"
ENV SHARP_IGNORE_GLOBAL_LIBVIPS=1

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
COPY pnpm-workspace.yaml* ./

RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3001

CMD ["pnpm", "dev"]
