<script lang="ts">
 import PageHeader from '$lib/admin/PageHeader.svelte'; import StatusBadge from '$lib/admin/StatusBadge.svelte'; import { formatDate } from '$lib/admin/format'; import { Button } from '$lib/components/ui/button'; import { Textarea } from '$lib/components/ui/textarea'; import { Label } from '$lib/components/ui/label'; import { Alert, AlertDescription } from '$lib/components/ui/alert'; import { Trash2 } from '@lucide/svelte'; import { enhance } from '$app/forms'; import { invalidateAll } from '$app/navigation'; import { toast } from 'svelte-sonner';
 let {data,form}=$props(); const row=$derived(data.letter); let rejection=$state(false); const update=()=>async({update}:any)=>{await update();await invalidateAll();toast.success('Status berhasil diperbarui')};
</script>
<PageHeader title={row.subject} description={`${row.letter_type} · ${row.ministry}`}><StatusBadge status={row.status}/></PageHeader>
{#if form?.error}<Alert variant="destructive" class="mb-4"><AlertDescription>{form.error}</AlertDescription></Alert>{/if}
<div class="grid gap-5 xl:grid-cols-[1fr_340px]"><article class="rounded-xl border bg-card p-6 md:p-10"><p class="text-xs font-semibold uppercase tracking-widest text-orange-500">Draft surat</p><h2 class="mt-2 font-serif text-2xl font-semibold">{row.subject}</h2><div class="mt-7 whitespace-pre-wrap border-t pt-7 font-serif text-[17px] leading-8 text-black-500">{row.body}</div></article><aside class="space-y-5"><section class="rounded-xl border bg-card p-5"><h2 class="font-serif text-lg font-semibold">Informasi</h2><dl class="mt-4 grid gap-3 text-sm"><div><dt class="text-muted-foreground">Deadline</dt><dd>{formatDate(row.deadline,true)}</dd></div><div><dt class="text-muted-foreground">Pengaju</dt><dd>{row.submitter?.name||'—'}</dd></div><div><dt class="text-muted-foreground">PJ</dt><dd>{row.assigned_pj?.name||'Belum ditetapkan'}</dd></div><div><dt class="text-muted-foreground">Diajukan</dt><dd>{formatDate(row.created_at,true)}</dd></div></dl></section>
{#if row.status==='PENDING'}<form method="POST" action="?/status" use:enhance={update} class="rounded-xl border bg-card p-5"><input type="hidden" name="status" value="IN_REVIEW"/><Button type="submit" class="w-full bg-blue-500">Mulai peninjauan</Button></form>{:else if row.status==='IN_REVIEW'}<form method="POST" action="?/status" use:enhance={update} class="space-y-3 rounded-xl border bg-card p-5"><h2 class="font-serif text-lg font-semibold">Keputusan</h2>{#if rejection}<Label for="notes">Alasan penolakan</Label><Textarea id="notes" name="notes" required/>{/if}<div class="grid grid-cols-2 gap-2"><Button type="submit" name="status" value="APPROVED" class="bg-green-700">Setujui</Button><Button type={rejection?'submit':'button'} name="status" value="REJECTED" variant="destructive" onclick={()=>rejection=true}>Tolak</Button></div></form>{/if}
{#if row.notes}<Alert><AlertDescription><strong>Catatan:</strong> {row.notes}</AlertDescription></Alert>{/if}<form method="POST" action="?/delete" onsubmit={(e)=>{if(!confirm('Hapus pengajuan surat ini?'))e.preventDefault()}}><Button type="submit" variant="ghost" class="w-full text-red-700"><Trash2/>Hapus pengajuan</Button></form></aside></div>
