<script lang="ts">
 import SubmissionTimeline from '$lib/admin/SubmissionTimeline.svelte'; import PageHeader from '$lib/admin/PageHeader.svelte'; import StatusBadge from '$lib/admin/StatusBadge.svelte'; import { formatDate } from '$lib/admin/format'; import { Button } from '$lib/components/ui/button'; import { Textarea } from '$lib/components/ui/textarea'; import { Label } from '$lib/components/ui/label'; import { Alert, AlertDescription } from '$lib/components/ui/alert'; import { Trash2 } from '@lucide/svelte'; import { enhance } from '$app/forms'; import { invalidateAll } from '$app/navigation'; import { toast } from 'svelte-sonner';
 let {data,form}=$props(); const row=$derived(data.letter); let rejection=$state(false); const update=()=>async({update}:any)=>{await update();await invalidateAll();toast.success('Status berhasil diperbarui')};
</script>
<PageHeader title={row.subject} description={`${row.letter_type} · ${row.ministry}`}><StatusBadge status={row.status}/></PageHeader>
{#if form?.error}<Alert variant="destructive" class="mb-4"><AlertDescription>{form.error}</AlertDescription></Alert>{/if}
<div class="grid gap-5 xl:grid-cols-[1fr_340px]"><article class="rounded-xl border bg-card p-6 md:p-10"><p class="text-xs font-semibold uppercase tracking-widest text-orange-500">Draft surat</p><h2 class="mt-2 font-serif text-2xl font-semibold">{row.subject}</h2><div class="mt-7 whitespace-pre-wrap border-t pt-7 font-serif text-[17px] leading-8 text-black-500">{row.body}</div><SubmissionTimeline history={data.timeline} /></article><aside class="space-y-5"><section class="rounded-xl border bg-card p-5"><h2 class="font-serif text-lg font-semibold">Informasi</h2><dl class="mt-4 grid gap-3 text-sm"><div><dt class="text-muted-foreground">Deadline</dt><dd>{formatDate(row.deadline,true)}</dd></div><div><dt class="text-muted-foreground">Pengaju</dt><dd>{row.submitter?.name||'—'}</dd></div><div><dt class="text-muted-foreground">PJ</dt><dd>{row.assigned_pj?.name||'Belum ditetapkan'}</dd></div><div><dt class="text-muted-foreground">Diajukan</dt><dd>{formatDate(row.created_at,true)}</dd></div></dl></section>
{#if data.user.role === "ADMIN_MEDINFO"}<form method="POST" action="?/assign" use:enhance={update} class="space-y-3 rounded-xl border border-blue-100 bg-blue-50/40 p-5"><h2 class="font-serif text-lg font-semibold">Assignment PJ</h2><Label for="assigned_pj_id">Pilih PJ Medinfo</Label><select id="assigned_pj_id" name="assigned_pj_id" required class="h-10 w-full rounded-lg border bg-white px-3 text-sm" value={row.assigned_pj_id || ""}><option value="" disabled>Belum ditetapkan</option>{#each data.queue as item}<option value={item.user_id} disabled={item.is_busy && item.user_id !== row.assigned_pj_id}>{item.user?.name || "PJ Medinfo"}{item.is_busy && item.user_id !== row.assigned_pj_id ? " · Sibuk: " + (item.active_task_title || item.active_request_code || "task aktif") : " · Tersedia"}</option>{/each}</select><Button type="submit" class="w-full bg-blue-500">Tetapkan PJ</Button></form>{/if}
{#if data.user.role === "ADMIN" && row.status === "REVISION_REQUIRED"}<form method="POST" action="?/revision" use:enhance={update} class="space-y-3 rounded-xl border border-orange-200 bg-orange-50/40 p-5"><h2 class="font-serif text-lg font-semibold">Kirim revisi surat</h2><Textarea name="notes" required placeholder="Ringkasan perbaikan..."/><Button type="submit" class="w-full bg-orange-500">Kirim revisi</Button></form>{/if}
{#if data.user.role==='ADMIN_MEDINFO' && row.status==='SUBMITTED'}<form method="POST" action="?/status" use:enhance={update} class="rounded-xl border bg-card p-5"><input type="hidden" name="status" value="PENDING_REVIEW"/><p class="mb-3 text-sm text-muted-foreground">{row.assigned_pj_id ? "PJ siap menangani pengajuan ini." : "Tetapkan PJ terlebih dahulu."}</p><Button type="submit" class="w-full bg-blue-500" disabled={!row.assigned_pj_id}>Mulai peninjauan</Button></form>{:else if data.user.role==='ADMIN_MEDINFO' && (row.status==='PENDING_REVIEW' || row.status==='REVISION_SUBMITTED')}<form method="POST" action="?/status" use:enhance={update} class="space-y-3 rounded-xl border bg-card p-5"><h2 class="font-serif text-lg font-semibold">Keputusan</h2><Label for="notes">Catatan review</Label><Textarea id="notes" name="notes" required/><div class="grid gap-2"><Button type="submit" name="status" value="APPROVED" class="bg-green-700">Setujui</Button><Button type="submit" name="status" value="REVISION_REQUIRED" variant="outline">Minta revisi</Button><Button type={rejection?'submit':'button'} name="status" value="REJECTED" variant="destructive" onclick={()=>rejection=true}>Tolak</Button></div></form>{/if}
{#if data.user.role === "ADMIN_MEDINFO" && row.status === "APPROVED"}<form method="POST" action="?/status" use:enhance={update} class="rounded-xl border bg-card p-5"><input type="hidden" name="status" value="COMPLETED"/><Button type="submit" class="w-full bg-green-700">Tandai surat selesai</Button></form>{/if}
{#if row.notes}<Alert><AlertDescription><strong>Catatan:</strong> {row.notes}</AlertDescription></Alert>{/if}{#if data.user.role === "ADMIN_MEDINFO"}<form method="POST" action="?/delete" onsubmit={(e)=>{if(!confirm('Hapus pengajuan surat ini?'))e.preventDefault()}}><Button type="submit" variant="ghost" class="w-full text-red-700"><Trash2/>Hapus pengajuan</Button></form>{/if}</aside></div>
